### ISSUE TITLE
Improve new user experience with release script

### ISSUE THREAD

**Issue by BryanCrotaz** [rwjblue/create-rwjblue-release-it-setup#11]
Add
```
"scripts": {
    "release": "release-it"
  },
```
And in readme, add instructions for running release:
```
yarn release --minor
-or-
npm run release --minor
```

Also add a `.release-it.js` file with the recommended defaults for ember apps

**Comment by rwjblue** [comment]
I had that originally, but there are loads of issues with authentication when running `yarn release`.

https://github.com/rwjblue/create-rwjblue-release-it-setup/pull/8

**Comment by rwjblue** [comment]
Some related issues:

* https://github.com/sindresorhus/np/issues/416
* https://github.com/release-it/release-it/issues/95
* https://github.com/yarnpkg/yarn/issues/5683

**Comment by rwjblue** [comment]
Going to close this for now, happy to continue discussion though!
